routes/web.php
<?php

use \App\Http\Controllers\UserController;
use \App\Http\Controllers\ListController;
use \App\Http\Controllers\CardController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// User

Route::get('/', function () {
    return view('Signup');
});
Route::get('/login', function () {
    return view('login');
})->name('login');
Route::post('/signup', [UserController::class, 'Signup'])->name('signup');
Route::post('/signin', [UserController::class, 'login'])->name('signin');
//Auth Middleware
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    });
    Route::get('/Create-new-user', [UserController::class, 'view_new_user'])->name('Create-new-user');
    Route::post('/new-user', [UserController::class, 'new_user'])->name('CreateUser');


//List
    Route::resource('lists', ListController::class);
//Cards

    Route::resource('cards', CardController::class);
});

resources/views/Cards.blade.php
@include('header');
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar');


        </div>
        <div class="col-9 pt-5">
            @if($errors->any())
                <h3> {{ implode('', $errors->all(':message')) }}</h3>
            @endif
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
            <h2>Add Cards</h2>
            <form method="post" action="{{route('cards.store')}}" enctype="multipart/form-data" >
                <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Card Title</label>
                    <input type="text" name="Title" class="form-control" id="title" aria-describedby="emailHelp">
                    <label for="exampleInputEmail1" class="form-label">List</label>
                    <select name="list-id" class="form-control">
                        @foreach($listdata as $list)
                        <option value="{{$list->id}}" >{{$list->Title}}</option>
                        @endforeach
                    </select>
                    <label for="exampleInputEmail1" class="form-label">Card Description</label>
                    <textarea class="form-control" cols="30" rows="2" name="Description"></textarea>
                    <label for="exampleInputEmail1" class="form-label pt-3">File</label>
                    <input type="file" name="file">
                </div>
                <button type="submit" class="btn btn-primary">Add Card</button>
            </form>

        </div>
    </div>
</div>
@include('footer');

resources/views/Showcards.blade.php
@include('header')
<div class="container">
    <div class="row">
        <div class="col-3 pt-5">
            @include('sidebar')


        </div>

        <div class="col-9">
            @if (Auth::check())
                @php
                    $role = Auth::user()->role;
                @endphp
            @endif;
            <h2>Cards</h2>
            @if($errors->any())
                <h3> {{ implode('', $errors->all(':message')) }}</h3>
            @endif
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <table>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>File/Image</th>
                    @if($role != 'only_view')
                        <th>Edit</th>
                        <th>Delete</th>
                    @endif
                </tr>
                @foreach($carddata as $card)
                    <tr>
                        <td>{{$card->Title}}</td>
                        <td>{{$card->Description}}</td>
                        <td><a href="{{ asset("/storage/uploads/".base64_decode($card->file))}}" download>Download</a>
                        </td>
                        @if($role != 'only_view')
                            <td><a href="{{route( 'cards.edit',$card->id )}}">Edit</td>
                            <td>
                                <form action="{{route('cards.destroy',$card->id )}}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE"/>
                                    <input type="submit" value="Delete">
                                </form>
                            </td>
                        @endif
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
@include('footer')

resources/views/Showlist.blade.php
@include('header')
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar')


        </div>
        <div class="col-9">
            <h2>Lists</h2>
            <table>
                <tr>
                    <th>Title</th>
                    <th>Progress bar</th>
                </tr>
                @foreach($listdata as $list)
                    <tr>
                        <td>{{$list->Title}}</td>
                        <td><label for="file">Card Complete progress:</label>
                            @foreach($cards as $card)

                                @if($card->list_id == $list->id)
                                    @php
                                        $count = App\Models\Card::where(['list_id' => $list->id])->count();

                                    @endphp

                                    <progress id="file" value="{{$count}}" max="100"> 32%</progress></td>

                        @endif
                        @endforeach
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
@include('footer')

resources/views/Signup.blade.php
@include('header')
<div class="container">
    <div class="row pt-5">
        <h2>Sign Up</h2>
        @if($errors->any())
            <div style="background-color:red" > {{ implode('', $errors->all(':message')) }}</div>
        @endif
        <form method="post" action="{{route('signup')}}" >
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="name" value="Name-admin">
            <input type="hidden" name="role" value="admin">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@include('footer')

resources/views/create_user.blade.php
@include('header')
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar')


        </div>
        <div class="col-9 pt-5">
            @if($errors->any())
                <h3> {{ implode('', $errors->all(':message')) }}</h3>
            @endif
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <h2>Add USer</h2>
                <form method="post" action="{{route('CreateUser')}}" >
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="name" value="Name-admin">
                    <input type="hidden" name="role" value="admin">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Email address</label>
                        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <select class="form-control" name="role">
                            <option value="edit_access" >Edit access</option>
                            <option value="only_view" >Only View</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

        </div>
    </div>
</div>
@include('footer')

resources/views/dashboard.blade.php
@include('header');
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar');


        </div>
        <div class="col-9">


        </div>
    </div>
</div>
@include('footer');

resources/views/editcard.blade.php
@include('header');
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar');


        </div>
        <div class="col-9 pt-5">
            @if($errors->any())
                <h3> {{ implode('', $errors->all(':message')) }}</h3>
            @endif
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <h2>Update Cards</h2>
            <form method="post" action="{{route('cards.update',$card->id)}}" enctype="multipart/form-data" >
                {{ method_field('PUT') }}
                <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Card Title</label>
                    <input type="text" name="Title" class="form-control" value="{{$card->Title}}" id="title" aria-describedby="emailHelp">
                    <label for="exampleInputEmail1" class="form-label">List</label>
                    <select name="list-id" class="form-control">
                        @foreach($listdata as $list)
                            <option value="{{$list->id}}" @if($list->id==$card->list_id){{'selected'}}@endif>{{$list->Title}}</option>
                        @endforeach
                    </select>
                    <label for="exampleInputEmail1" class="form-label">Card Description</label>
                    <textarea class="form-control" cols="30" rows="2" name="Description">{{$card->Description}}</textarea>
                    <label for="exampleInputEmail1" class="form-label pt-3">File</label>
                    <input type="file" name="file" value="{{base64_decode($card->file)}}"><a href="{{ asset("/storage/uploads/".base64_decode($card->file))}}" download>Old File Download</a><br>
                    <label for="exampleInputEmail1" class="form-label pt-3">Task Card</label><br>
                    <input type="checkbox"  name="In_complete_checkbox" value="Yes"  @if($card->In_complete_checkbox=='Yes'){{'checked'}}@endif>
                    <label for="vehicle1">Complete Task Card</label><br>
                </div>
                <button type="submit" class="btn btn-primary">Update Card</button>
            </form>

        </div>
    </div>
</div>
@include('footer');

resources/views/footer.blade.php
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

resources/views/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title></title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>

resources/views/list.blade.php
@include('header')
<div class="container">
    <div class="row">
        <div class="col-3">
            @include('sidebar')
        </div>
        <div class="col-9 pt-5">
            @if($errors->any())
                <h3> {{ implode('', $errors->all(':message')) }}</h3>
            @endif
                @if(session()->has('message'))
                    <div class="alert alert-success">
                        {{ session()->get('message') }}
                    </div>
                @endif
            <h2>Add List</h2>
            <form method="post" action="{{route('lists.store')}}" >
                <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">List Title</label>
                    <input type="text" name="Title" class="form-control" id="title" aria-describedby="emailHelp">
                </div>
                <button type="submit" class="btn btn-primary">Add List</button>
            </form>

        </div>
    </div>
</div>
@include('footer')

resources/views/login.blade.php
@include('header')
<div class="container">
    <div class="row pt-5">
        <h2>Login</h2>
        @if($errors->any())
            <div style="background-color:red" > {{ implode('', $errors->all(':message')) }}</div>
        @endif
        <form method="post" action="{{route('signin')}}" >
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@include('footer');

resources/views/sidebar.blade.php
<div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Menu Sidebar</h3>
        </div>
        @if (Auth::check())
            @php
                $role = Auth::user()->role;
            @endphp

            @if($role == 'only_view')
                <ul class="list-unstyled components">
                    <li><a href="{{route('lists.create')}}">Show all List</a></li>
                    <li><a href="{{route('cards.create')}}">Show all Cards</a></li>
                </ul>
            @else
                <ul class="list-unstyled components">
                    <li>
                        <a href="{{route('lists.index')}}">Add Lists</a>
                        <ul>
                            <li><a href="{{route('lists.create')}}">Show all List</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{route('cards.index')}}">Add Cards</a>
                        <ul>
                            <li><a href="{{route('cards.create')}}">Show all Cards</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{route('Create-new-user')}}">Add User</a>
                    </li>

                </ul>
            @endif
        @endif
    </nav>
</div>